title: "Joe Zlonicky"
author: "Joe Zlonicky"
description: "Made using <b><a href=\"https://jekyllrb.com\">Jekyll</a></b> and <b><a href=\"https://github.com/niklasbuschmann/contrast\">contrast</a></b> theme"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.html"}

external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/joezlonicky"}
  - {title: Itch.io, icon: itch-io, url: "https://joezlonicky.itch.io/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

plugins:
  - jekyll-feed
